name: mikhmon-v3
services:
    mikhmon:
        cpu_shares: 90
        command:
            - php
            - -S
            - 0.0.0.0:8000
            - -t
            - /var/www
        container_name: mikhmon
        deploy:
            resources:
                limits:
                    memory: "2147483648"
        environment:
            MIKHMON_ENV: production
            MIKHMON_SECRET: 7b802786bff89093fc91b651cbe18c095fbb02c6201c21e340fce2387eea062d
            MIKHMON_SESSION_NAME: mkhm_sess
        env_file:
            - /root/main-app/mikhmon-v3/.env
        hostname: mikhmon
        image: php:7.4-cli
        networks:
            mikhmon_network: null
        ports:
            - mode: ingress
              target: 8000
              published: "999"
              protocol: tcp
        restart: unless-stopped
        tty: true
        volumes:
            - type: bind
              source: /root/main-app/mikhmon-v3
              target: /var/www
              bind:
                create_host_path: true
        working_dir: /var/www
networks:
    default:
        name: mikhmon-v3_default
    mikhmon_network:
        name: mikhmon-v3_mikhmon_network
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/24
x-casaos:
    author: self
    category: self
    hostname: mikhmon.thehanifz.com
    icon: ""
    index: /
    is_uncontrolled: false
    port_map: ""
    scheme: https
    title:
        custom: 'mikhmon online '
